// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnemryazblsivtsxxwml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZW1yeWF6YmxzaXZ0c3h4d21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjA4NzYsImV4cCI6MjA2OTY5Njg3Nn0.fR-wg5hdcAkZDhVVZNZfK0kd3qreQZyv2KVrthHpOTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});